# Generated by Django 5.2.7 on 2025-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("ISBN", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("explanation", models.CharField(max_length=150)),
                ("publisher", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("year", models.DateField()),
                ("image", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("borrowed", "Borrowed"),
                            ("late", "Late"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
