# Generated by Django 5.2.7 on 2025-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
