# Generated by Django 5.2.7 on 2025-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="explanation",
            field=models.TextField(),
        ),
    ]
