# Generated by Django 5.2.7 on 2025-11-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0003_alter_book_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
