# Generated by Django 5.2.8 on 2025-11-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fine",
            fields=[
                ("Fine_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField()),
                (
                    "Status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid")], max_length=20
                    ),
                ),
                ("Amount", models.FloatField()),
                (
                    "Staff_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines_as_staff",
                        to="user.staff",
                    ),
                ),
                (
                    "Student_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines_as_student",
                        to="user.student",
                    ),
                ),
            ],
        ),
    ]
