# Generated by Django 5.2.7 on 2025-11-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barrow", "0001_initial"),
        ("fine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="Borrow_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fines",
                to="Barrow.borrow",
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="Payment_Date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
