# Generated by Django 5.2.7 on 2025-11-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barrow", "0002_alter_borrow_student"),
        ("fine", "0002_fine_borrow_id_fine_payment_date"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="Borrow_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fines",
                to="Barrow.borrow",
            ),
        ),
        migrations.AlterField(
            model_name="fine",
            name="Staff_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fines_as_staff",
                to="user.staff",
            ),
        ),
        migrations.AlterField(
            model_name="fine",
            name="Student_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fines_as_student",
                to="user.student",
            ),
        ),
    ]
