# Generated by Django 5.2.8 on 2025-12-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barrow", "0002_alter_borrow_student"),
        ("fine", "0003_alter_fine_borrow_id_alter_fine_staff_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="Borrow_ID",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fine",
                to="Barrow.borrow",
            ),
        ),
    ]
