# Generated by Django 5.2.7 on 2025-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Password",
            field=models.CharField(max_length=128),
        ),
    ]
