# Generated by Django 5.2.8 on 2025-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="Phone",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="Username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
