# Generated by Django 5.2.7 on 2025-11-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barrow", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "member"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_borrows",
                to="user.student",
            ),
        ),
    ]
